### ISSUE TITLE
params | cmd: Provide ability to specify network to user

### ISSUE THREAD

**Issue by Bidon15** [celestiaorg/celestia-node#1066]
Remove panic when using `CELESTIA_CUSTOM` during re-init
Currently, node panics when we try to re-initialize an existing store. 
Maybe an error log with confirmation flag `--yes` to proceed further can help eliminate this over-protective behaviour

**Comment by renaynay** [comment]
We need to have a more sophisticated approach to this in order to prevent users from accidentally having `CELESTIA_CUSTOM` set and corrupting their store by trying to sync a different network over an existing store. 

There is now also the issue that there are two networks -- `arabica` and `mamaki` that users may want to connect to. We need to handle this multi-network situation gracefully. I agree a panic is not the way to do it. We have an ongoing discussion thread about it in slack, but we should move that discussion here.

**Comment by SweeXordious** [comment]
I guess there are two parts to the discussion at hand: the first is for the binary, and the second is for the docker image.

Currently, the binary when executing, if I understand right:

- `init`: it takes the `CELESTIA_CUSTOM` env variable and uses it to `init` the store.
- `start`: doesn't care about `CELESTIA_CUSTOM` env variable and just runs the provided node store.

To me, this is the right behavior for the binary and nothing should be changed.

However, when it comes to the docker image, it always runs the following:

https://github.com/celestiaorg/celestia-node/blob/8657edc37d3911d42de447d9d0c93c4676a148c9/docker/entrypoint.sh#L5-L11

This initializes the node store using the env variable, then starts the node. And this is where I think is the issue.

While having the container doing the initialization step for you is good since it makes it easy for end users to run the node software. It stills blocks separating the initialization and the start of the node for others who want to customize it.
For example, @sysrex had to override the `ENTRYPOINT` for the latest `arabica` deployment. Correct me if I am wrong, please.

Thus, I guess the discussion should be around the docker image `ENTRYPOINT` and whether it makes sense for it to always initialize the store or not. 

Pros: easier user experience, even though I don't think normal users would use docker and stuff to run the software.
Cons: makes it harder for developers to use the node image without overriding the entrypoint.

And the other way around.

**Comment by renaynay** [comment]
# ideas

* Private option via `CELESTIA_PRIVATE_GENESIS` ❌ 
* Custom option via `CELESTIA_CUSTOM` and clean up the handling of re-init || discuss node store naming
* * `CELESTIA_CUSTOM=private:<gen_hash>:bootstrappers_list`

introduce a flag `--network <network_name>`
--> checks network name against the registered inside params and if exists, run on network

```
--network < arabica || mamaki > 
```

issues that remain: 
* node store naming
** `$HOME/.celestia-light-<network_name>`
* do we provide custom option for `--network` ?
* if we keep CELESTIA_CUSTOM env var, how do we go about re-init protection (related to node store naming)

# decision

* Re: node store, extend home directory with network name
* Keep `CELESTIA_CUSTOM`, deprecate `CELESTIA_PRIVATE_GENESIS`
* * panic will be taken care of by the node store naming extension
* Add `--network < arabica || mamaki >`

# potential considerations
maybe have the directory be `$HOME/.celestia/light-<network_name>`
