### ISSUE TITLE
share/ipld: Remove duplicated namespace appended by NMTWrapper

### ISSUE THREAD

**Issue by renaynay** [celestiaorg/celestia-node#1239]
### Context

The NMTWrapper in celestia-core prepends to share (leaf nodes) an additional namespace, which is just a copy of real namespaces or the constant parity namespace.

### Goal

Optimize data storage and network by removing this additional prepended namespace and automatically prepend it where needed. 

### Refs
https://github.com/celestiaorg/nmt/issues/55#issuecomment-1118931841

**Comment by Wondertan** [comment]
Unfortunately, we cannot implement this(in a clean way without introducing additional complexity). 

If we want to cut the additional namespace added by NMTWrapper, then we should add it back [once we receive it from the network](https://github.com/celestiaorg/celestia-node/blob/main/share/ipld/namespace_hasher.go#L69) so that we can properly verify the integrity. Doing this requires `namespaceHasher` to know from which quadrant the share data is coming, which is not possible
