### ISSUE TITLE
fix(tests): remove `testing.T` as parameter from testing utilities

### ISSUE THREAD

**Issue by distractedm1nd** [celestiaorg/celestia-node#1275]
Personal preference, I would structure helper functions as stand alone functions. I don't think they need to have the tester passed through. I think it is cleaner to just return an error and have the calling test handle the testing failure.  

This then also allows us to test these functions to ensure that our tests are using sound functions and we aren't building tests off of faulty helpers.

_Originally posted by @MSevey in https://github.com/celestiaorg/celestia-node/pull/1197#discussion_r1003468884_

**Comment by renaynay** [comment]
Use `t.Helper()` in test utillity functions and keep passing `testing.T`

**Comment by MSevey** [comment]
> Use `t.Helper()` in test utillity functions and keep passing `testing.T`

Part of my point was that there isn't a need to submit the `testing.T` to that helper function at all.  What is the benefit of having the `testing.T` available in that function vs just returning an error?

**Comment by Wondertan** [comment]
@MSevey, what's the benefit of changing this besides personal preference? 

Passing T to test funcs is the pattern we are used to and following for a while, and there should be a good argument if we want to change and spend time on this.

**Comment by renaynay** [comment]
https://pkg.go.dev/testing#T.Helper

**Comment by MSevey** [comment]
Passing the `testing.T` into the method, just to call `t.Error` or similar function, reduces the flexibility of the helper method. 

For example, image we have a simple helper that checks a condition. If we pass in the `testing.T` it looks like so:
```go
func helper(t testing.T, args ...args) {
  if condition {
    t.Error()
  } 
  return 
}
```

In this case, tests are only able to use this helper in the happy case. They are not able to use this helper to verify a false case, because the test would error out and fail. 

An example here of when you would want to verify both cases would be using a helper method to verify that two nodes are synced. In order to fully test certain scenarios the test would want to be able to use the helper method to know when nodes are both synced and not synced. 

Additionally for the standard of using it as part of the all test helpers, this means we aren't able to full test the testing infrastructure code that our tests are building built on. Having testing for our testing infrastructure is one way to reduce `flakiness` because we are actively verifying the state of our testers and have a mechanism to stress test them. One example here is being able to see how many test nodes you can spin up before you hit system limitations like `port already in use`. 

Also it leads to functions like this:
```go
// RandBlockID provides a BlockID fixture.
func RandBlockID(t *testing.T) types.BlockID {
	bid := types.BlockID{
		Hash: make([]byte, 32),
		PartSetHeader: types.PartSetHeader{
			Total: 123,
			Hash:  make([]byte, 32),
		},
	}
	mrand.Read(bid.Hash)
	mrand.Read(bid.PartSetHeader.Hash)
	return bid
}
```
Where I'm surprised the linter doesn't complain about this function because the `testing.T` is not used in the function at all. 

What was the reason we went with this standard in the first place? Was there a specific testing standard we were trying to follow?

**Comment by MSevey** [comment]
Additionally it is a general design pattern around where the decision logic is. Right now the helpers hold the decision logic around test failures, which I think is a little backwards because then every test must hold the same assumptions in order to use the helpers. 

IMO it is much better for the tests to hold all the decision logic as to what constitutes a failure and the helpers are all unaware of what the tests are doing. 

When the test helpers hold that decision logic it adds layers of complexity and requires additional contextual knowledge of the code base in order to use them properly.
