### ISSUE TITLE
header/core: Investigate if tendermint implements server-side header range limit and implement on `CoreExchange`

### ISSUE THREAD

**Issue by renaynay** [celestiaorg/celestia-node#1282]
`CoreExchange` and `P2PExchange` clients should have the same behaviour for their implementations. Specifically `GetRangeByHeight` short circuits if > `maxRequestSize` so we should have a similar `maxRequestSize` limit on the `CoreExchange` side.

**Comment by vgonkivs** [comment]
We don't have any limits on GetRangebyHeight because the implementation provides a sequential call `GetByHeight` for every header in range.

<img width="917" alt="Снимок экрана 2022-11-01 в 12 19 02" src="https://user-images.githubusercontent.com/40579846/199222397-837245d2-26c6-4787-818c-f0ffd43495d1.png">
