### ISSUE TITLE
rpc: decide on versioning

### ISSUE THREAD

**Issue by distractedm1nd** [celestiaorg/celestia-node#1345]
We need to make a decision on how we want to version our RPC. In the future we could provide multiple versions at multiple endpoints. At the very least, it will be a failsafe for someone accidentally trying to use an old version of our api

We can then provide the first RPC at `/v1` for example

Also: return it as part of `node.Info`

**Comment by renaynay** [comment]
We can add standard versioning to the gateway starting at v1 but for json rpc, I propose just versioning it via an endpoint that can be provided on the `NodeModule` since that's where all admin-related info lives. In Lotus, they just have an endpoint on the common API that returns the version as an encoded uint32. I feel like it's overkill and we can just return a string :)

**Comment by renaynay** [comment]
Alternatively, we could explore something related to the discussion [here](https://github.com/decred/dcrd/issues/2746#issue-997383784). But IMO this is a later consideration and something we should think about from a devX perspective (probably loop in @YazzyYaz)

**Comment by renaynay** [comment]
As another alternative, we could think about versioning the namespaces under which our modules are registered, but I think that's hairy.

**Comment by Wondertan** [comment]
> As another alternative, we could think about versioning the namespaces under which our modules are registered, but I think that's hairy.

This is the correct approach IMO. Wouldn't say it's hairy but it adds some overhead for sure.

**Comment by renaynay** [comment]
<img width="566" alt="Screenshot 2023-03-13 at 09 37 04" src="https://user-images.githubusercontent.com/41963722/224648872-55b96f6e-4db8-4d4e-aaa8-7917bd321374.png">

 🤷🏻
