### ISSUE TITLE
fraud: use `header/mocks.Store` instead of custom `mockStore` 

### ISSUE THREAD

**Issue by Wondertan** [celestiaorg/celestia-node#1542]
Right now, we define there a custom `mockStore`, which is basically a copy of existing reusable mock

**Comment by richardgreg** [comment]
Hi, I'd like to work on this

**Comment by richardgreg** [comment]
Hi, sorry this is taking a minute. I am new to GO, and I come from a Python background. So you can understand there's quite a lot I must learn and unlearn.

I think I understand the problem and what's expected of me: in `header/mocks/store`, there's a struct `MockStore`. I should import and use that in `fraud/testing` instead of the custom `mockStore`.

**Comment by Wondertan** [comment]
Exactly @richardgreg

**Comment by richardgreg** [comment]
@Wondertan, a new PR ([7a2f03202afcaf9eef91f8371f78bd939a41e3a57fea6a51e42c60ec1ccdebda](https://github.com/celestiaorg/celestia-node/commit/a3137ba70055926db23234a7145392054882bd11#diff-7a2f03202afcaf9eef91f8371f78bd939a41e3a57fea6a51e42c60ec1ccdebda)) has made modifications to `header/mocks.Store`. I'll need to import `libs/header` to use the new generic `mockStore`. This new header pkg does not have `ExtendedHeader`

**Comment by Wondertan** [comment]
Closed by https://github.com/celestiaorg/celestia-node/pull/2039
