### ISSUE TITLE
Improve rpc use help command

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/celestia-node#2343]
## Context

https://github.com/celestiaorg/celestia-node/blob/a2685d47a2ca1164cb1cd6d579b849a4f8372a80/cmd/celestia/rpc.go#L73

## Problem

I don't think the order of these arguments is correct. It looks like `[method]` goes before `[namespace]` based on the repro steps in https://github.com/celestiaorg/celestia-node/issues/2321
2. What does `namespace` refer to? A full 29 byte namespace? Just the 28 byte namespace ID? Or just the 10 byte user-specified namespace ID for a v0 namespace?

## Proposal

1. Fix the order of params in the help message
1. Provide a `Long` message that explains what a `namespace` is

**Comment by distractedm1nd** [comment]
@rootulp Namespace refers to the RPC namespace, aka the module. So `celestia rpc blob Submit [params...]` for example

**Comment by distractedm1nd** [comment]
With regards to what namespace refers to in the usage of state.SubmitPayForBlob and blob.Submit, we can explain in the actual docs/tutorial - cc @jcstein 

The wished usage is that a user can:
- Submit a nID in either hex or base64
- When the nID is less than/equal to 10 bytes, it makes a v0 namespace out of it
- Otherwise, the namespace must be 29 bytes, including the version.

The reason for allowing a user to submit 10 or less bytes is because it is very clunky for users trying to experiment to have to look up the namespace rules and count that many bytes/use a tool to generate a namespace. It is much easier to just pass something like 0xDEADBEEF, and I assume most users will do this instead of reading docs to figure out they need to pass 0x000000000000000000000000000000000000000000000000deadbeef

**Comment by rootulp** [comment]
> @rootulp Namespace refers to the RPC namespace, aka the module. So `celestia rpc blob Submit [params...]` for example

Ahh that makes sense, thanks for explaining. Totally optional but it may reduce confusion if `[namespace]` was replaced with `[module]`.

Also totally onboard with these desired criteria:

> - Submit a nID in either hex or base64
> - When the nID is less than/equal to 10 bytes, it makes a v0 namespace out of it

but I'm not convinced the third one is strictly necessary. Defer to ya'll if you want to support it though.

**Comment by Wondertan** [comment]
[module] makes more sense; thanks for the suggestion. The [namespace] terminology comes from the rpc library we use.

**Comment by liamsi** [comment]
FWIW, the output here should be self-contained
`celestia rpc --help` should also list the modules/namespaces instead of forcing people to look into the docs. Or at the very least, there should be a link in the output where to find further info.
