### ISSUE TITLE
Introduce a new variable for clarity

### ISSUE THREAD

**Issue by andrijamitrovic23** [celestiaorg/celestia-node#2392]
In the [Validate](https://github.com/celestiaorg/celestia-node/blob/0823f6b644eb6ba176ef5ae3c008c65018ed5f46/share/eds/byzantine/bad_encoding.go#L113-L113) function, `merkleRowRoots` and `merkleColRoots` variables are used. `len(merkleRowRoots)` is used to check the size of `p.Shares`. One minor improvement for clarity would be to factor out the `len(merkleRowRoots)` as a separate variable because there is no equivalence between `p.Shares` and `merkleRowRoots`.

**Comment by rootulp** [comment]
I think this issue is referring to [this check](https://github.com/celestiaorg/celestia-node/blob/0823f6b644eb6ba176ef5ae3c008c65018ed5f46/share/eds/byzantine/bad_encoding.go#L135-L137). `len(p.Shares)` is expected to == `len(merkleRoots)` because `p.Shares` should contain all the shares for an EDS row or column. In this context, `len(merkleRoots)` is used to determine the width of the extended data square.
