### ISSUE TITLE
[Feature Request]: match upcoming node version with API

### ISSUE THREAD

**Issue by jcstein** [celestiaorg/celestia-node#2549]
### Implementation ideas

https://github.com/celestiaorg/celestia-node/pull/2521#issuecomment-1667938153

celestia-node v0.12.0-rc0 = api v0.12.0-rc0

**Comment by jcstein** [comment]
for example, if I check out to v0.12.1 of celestia-node and then run make openrpc-gen, the version reflected is v0.11.0 instead of v0.12.1

**Comment by jcstein** [comment]
checking in on this 👀 or are we going to stick with different versioning?

**Comment by jcstein** [comment]
api specs generated still show v0.11.0 as of v0.13.3 release

**Comment by jcstein** [comment]
https://github.com/celestiaorg/celestia-node/blob/332739f9e68196333bd1dea76fbeaac0f12737f8/nodebuilder/node/admin.go#L13

**Comment by vgonkivs** [comment]
To resolve this issue, we need to set [SemanticVersion](https://github.com/celestiaorg/celestia-node/blob/6382dc13b92d7b40077154aab823367500371cb8/nodebuilder/node/buildInfo.go#L21) instead of the hardcoded value. In this case, `docgen` cmd should be a part of the node binary to get the correct semantic version: 
`celestia docgen ...`

cc @distractedm1nd @Wondertan

**Comment by distractedm1nd** [comment]
Good idea 👍🏼 I'm on board
