### ISSUE TITLE
`GetSharesByNamespace` should get shares by reading them in the CAR file sequentially, rather than walking the IPLD

### ISSUE THREAD

**Issue by musalbas** [celestiaorg/celestia-node#2618]
This will allow us to remove the CAR index and inverted index for shrex-ND, and will result in much faster shrex-ND store performance.

**Comment by derrandz** [comment]
I've explored this a bit, and it seems that `GetSharesByNamespace` includes proofs for the shares it provides, and that requires traversing the tree down to determine the proof nodes of the retrieved shares.

With that being said, the inner nodes are of course also included in the CAR file, what I can't determine yet, is how to filter out only the proof nodes required for the filtered shares by namespace that have been retrieved from the CAR file.

I am probably overlooking something, is there a way to do this? cc @Wondertan @vgonkivs

**Comment by derrandz** [comment]
Will give this a go and propose a PR

**Comment by walldiss** [comment]
Actually shrex-ND doesn't use inverted_index, because it knows the required datahash from shrex-nd request. Implementing this is required to get rid of CAR index, but now enough. There also needs to be support for for bitswap to read shares without using CAR index. 
This one should be less of a priority compared to https://github.com/celestiaorg/celestia-node/issues/2479 (will allow to remove inverted_index) and pruning.

**Comment by musalbas** [comment]
As part of https://github.com/celestiaorg/celestia-node/issues/2615#issuecomment-1696371526, this will allow us to remove CAR index for blocks outside of the storage window, because sampling doesn't need to be supported for blocks that are pruned by the network.
