### ISSUE TITLE
Celestia light node storage filling up quickly

### ISSUE THREAD

**Issue by Alper2022** [celestiaorg/celestia-node#3352]
Hello!

I am currently running 4 celestia light nodes on a cluster of Raspberry Pi's i had lying around, all of them pi 4's with a 64gb storage card and 8gb of ram.

The issue i currently am noticing is, when running these nodes they QUICKLY fill up all the space on the disk, most of the space being lost to ~/.celestia-light/data/

My question basically is:

Is it normal for ~/.celestia-light/data/ to completely fill up, and end up shutting down the light node? or am i forgetting a configuration?

Thank you for your time and attention!

with kind regards,
Alper

edit: the command i run the nodes with is "nohup celestia light &"

**Comment by ramin** [comment]
hi @Alper2022 no that doesn't sound normal. Are there any logs you can share? Also, not sure if a typo or not, but you should start the light node with `celestia light start` (having completed init previously). Can you verify that is the starting command, I'd recommend revisiting the docs here https://docs.celestia.org/nodes/light-node

**Comment by walldiss** [comment]
Hello @Alper2022! Thank you for bringing this to our attention. It seems that your node was initialized with an earlier version of our software, which could use up to 64GB of storage because it lacked the sampling window feature. This feature allows the node to store data starting from 30 days prior to initialization. Currently, there is no automatic cleanup for storage, so the size will continue to grow over time. We are actively developing a solution known as "light node pruning."

To address this issue immediately, please upgrade to our latest version, v0.13.4, and reinitialize your node. A node initialized with this version should only occupy around 33GB, storing samples from the last 30 days only. Here's how you can upgrade and reinitialize your node:

- Delete the ~/.celestia-light directory to force a resync.
- Run celestia-node init followed by celestia-node start.

This process will reset your keys, so please contact us if you need assistance in preserving them. We are also developing a pruning features to further address storage growth in light nodes, which will be available in a future updates.

**Comment by jcstein** [comment]
@Alper2022 what version of celestia-node are you on?

**Comment by walldiss** [comment]
You are right, you just need to persist `~/.celestia-light/keys` folder to keep the keys

**Comment by ramin** [comment]
@Alper2022 how did test go?
