### ISSUE TITLE
node: Light node can be initialised with multiple trusted peers

### ISSUE THREAD

**Issue by Bidon15** [celestiaorg/celestia-node#364]
### Summary

Light node needs more options to include in trusted peers instead of 1

### Impact on users

In current implementation, a light node can be only initialised with 1 trusted peer. It will be beneficial to allow multiple trusted peers (array of them) for light node initialisation

**Comment by Wondertan** [comment]
We need this sooner than later. The issue is that after we start to rely on hardcoded bootstrap peers as default trusted peer, we will create a choke point around one only trusted peer, while we have multiple of them. Also, having multiple trusted peers will also load balance synchronization between them.

**Comment by Wondertan** [comment]
We should also retry over multiple trusted peers.

**Comment by Wondertan** [comment]
* While implementing this issue, we should also make use of bootstrap peers from the ‘params’ package if no trusted peers were given. Similar to how trustedHash is taken from ‘params’ if it's not given.
* P2PExchange should randomly choose one of the given trustedPeers and rely on it throughout runtime
