### ISSUE TITLE
CI: docgen doesn't build on v0.16.0, v0.17.1, v0.17.2

### ISSUE THREAD

**Issue by jcstein** [celestiaorg/celestia-node#3850]
Docgen didn't build on releases

**Comment by walldiss** [comment]
CI for doc gen failed due to previous step of go-releaser failing. Reference:
https://github.com/celestiaorg/celestia-node/actions/runs/11256100269

Error from CI:

⨯ release failed after 8m19s               error=scm releases: failed to publish artifacts: failed to upload celestia-node_Darwin_arm64.tar.gz after 1 tries: POST https://uploads.github.com/repos/celestiaorg/celestia-node/releases/178898505/assets?name=celestia-node_Darwin_arm64.tar.gz: 422 Validation Failed [{Resource:ReleaseAsset Field:name Code:already_exists Message:}]

**Comment by cristaloleg** [comment]
Should be fixed by https://github.com/celestiaorg/celestia-node/pull/3877

**Comment by renaynay** [comment]
@jcstein is it fixed now?

**Comment by jcstein** [comment]
it seems to be resolved beginning with https://github.com/celestiaorg/celestia-node/releases/tag/v0.20.0-arabica

will reopen if issues!
