### ISSUE TITLE
swamp: Integration tests with celestia-app instead of kvstore

### ISSUE THREAD

**Issue by liamsi** [celestiaorg/celestia-node#628]
### Implementation ideas

Use the app in swamp tests: https://github.com/celestiaorg/celestia-node/pull/626#issuecomment-1100609951

**Comment by evan-forbes** [comment]
This will need to change before we can upgrade to v0.7.0 of the app. This is due to the new processing that must occur to block data before it can properly split into shares, along with the complete removal of deprecated share encoding logic in core (`ComputeShares`).

This could occur via two ways. We started on a [solution](https://github.com/celestiaorg/celestia-app/commit/5db77f3c3866ec22697b421704ef23988fec5af8) that would likely require less refactoring of the swamp test, but this functionality is also already implemented in our own integration [test suite](https://github.com/celestiaorg/celestia-app/blob/main/testutil/network/network.go). The latter might be more useful, since it also does some initialization necessary to generate many different PFDs at once.
