### ISSUE TITLE
Test utilities should not be included in binary

### ISSUE THREAD

**Issue by Wondertan** [celestiaorg/celestia-node#688]
Currently, we have plenty of test utilities defined in files without `_test` prefix, which means they are included in the binary. Instead, we should either add the prefix or extract test utilities in sub pkgs, that are only imported by the test The best option can be chosen depending on the use case.

**Comment by adlerjohn** [comment]
> which means they are included in the binary

Does the optimizer not remove dead code? There's no way to reach the test functions from `main`, unless they're exported. Go noob here so please be gentle.

**Comment by ramin** [comment]
i've done a review of this, and we appear to have cleaned this up a lot since 2022. The only argument could be to move the "testing.go" files that are spread around packages to a `testing/helpers` or `testing/utils` package, but we've been quite diligent about these only being imported by _test.go files as is, and it already is a nice organizational pattern so not urgent and quite a change for the same outcome
