### ISSUE TITLE
cmd: OTLP TLS connection

### ISSUE THREAD

**Issue by Wondertan** [celestiaorg/celestia-node#934]
Currently, Otel data is transferred with OTLP over a plain HTTP connection, and instead, we should use TLS for data protection reasons.

To do this, we need to stop using [WithInsecure](https://github.com/open-telemetry/opentelemetry-go/blob/main/exporters/otlp/otlpmetric/otlpmetrichttp/options.go#L161) option for both metrics and tracing. Next, we should consider if using the default TLS configuration works for us and if not use [WithTLSClientConfig](https://github.com/open-telemetry/opentelemetry-go/blob/main/exporters/otlp/otlpmetric/otlpmetrichttp/options.go#L155).

**Comment by rootulp** [comment]
@Wondertan you're right. We want to remove `WithInsecure` or gate it behind a CLI flag like `--insecure-metrics` so that node operators don't have to configure self-signed certs if they're sending metrics to a self-hosted OTEL collector.

For incentivized testnet, we will run an OTEL Collector with a public certificate so we will do https://github.com/celestiaorg/celestia-node/pull/922/files#diff-0996f33be3bfe93470400ae686cb4040bc1eea9ebdc37d162f30e3d97d854d04R168-R185 

If we get feature requests from node operators to add support for sending data over HTTPS between celestia-node and OTEL Collector (without public certificates), we can implement it via https://github.com/celestiaorg/celestia-node/pull/922/files#diff-0996f33be3bfe93470400ae686cb4040bc1eea9ebdc37d162f30e3d97d854d04R187-R205

**Comment by Wondertan** [comment]
Ok, let's go this way. Running securely for the local case is unnecessary, so I made the `--metrics/tracing.tls` flag, which is on by default but can be turned off for local setup.
